### ISSUE TITLE
可以提供第二版的英文原版么？

### ISSUE THREAD

**Issue by shichaoyuan** [xiaoweiChen/CPP-Concurrency-In-Action-2ed-2019#1]
RT

**Comment by xiaoweiChen** [comment]
抱歉，这个我可能不能直接进行提供。这个库只提供个人翻译，并尊重原作者的知识产权。
可以提供我获取本书的地址，获取书籍要花点钱，是否值得就自己斟酌吧 ：）

https://blog.csdn.net/andersonliu_/article/details/86940113

**Comment by chaosink** [comment]
谢谢你的翻译工作！
我好奇的一点是，这样的翻译真的不构成侵权吗？

**Comment by xiaoweiChen** [comment]
@chaosink 不同于商业出版译文，开源的个人翻译属于灰色地带，在作者不追究的前提下，可以看作是个人的笔记。

**Comment by xiaoweiChen** [comment]
原版是下载 https://ru.b-ok2.org/book/3688262/d57395?dsource=recommend
