### ISSUE TITLE
这么快，第二版全译完了吗

### ISSUE THREAD

**Issue by l1t1** [xiaoweiChen/CPP-Concurrency-In-Action-2ed-2019#2]
是做的第一和二版的比较，增量翻译吗

**Comment by xiaoweiChen** [comment]
翻译过程中对比了第一版和第二版，第二版完全能包含第一版。所以在之前翻译第一版的基础上进行校对和翻译就比较快。

嗯，因为只有我自己一个人做这个事，且恰好赶上休假，所以尽快把第二版翻出来了。原本估计的工作量要到6月份之后才能完成。

本库不是增量翻译的。全部内容都有的。

**Comment by l1t1** [comment]
谢谢，这里(  http://m.newsmth.net/article/CPlusPlus/405222?p=5 )提到另一本，你看讲得怎么样
http://neilrieck.net/misc/pdf/computer-docs/parallel-programming-hard.pdf

**Comment by xiaoweiChen** [comment]
大致看了下，感觉是教如何使用并发的。如果对于并发和并行原理上的东西弄的不是很明白，感觉可以看下你你提供的这本书。600+页，没有细看，如果有误还望见谅。

论坛的留言也看了下，《C++ Concurrency In Action》这本书里面的东西并不是立马能用的东西，它里面更多的是告诉你使用C++的新标准怎么去玩并发和并行，所以里面的实现并非最高效，仅是一个示例，用于让读者通过阅读源码更容易明白作者想要表达的意图。如果对并行和并发非常了解的人们，会觉得这本书么什么意义，因为这本书并不适合他们。这本书更适合想要了解C++新标准且是初级并发或没有接触过并发的开发者。

**Comment by l1t1** [comment]
谢谢。那本书网上也有中文译文，也出版了，你的译文有出版计划吗？

**Comment by xiaoweiChen** [comment]
没有版权，不考虑出版。共享给大家看，一起帮忙完善就好。
