### ISSUE TITLE
第五章一些问题的商讨

### ISSUE THREAD

**Issue by mapleFU** [xiaoweiChen/CPP-Concurrency-In-Action-2ed-2019#21]
首先感谢作者翻译。但是个人感觉第五章的 load, store, 以及各种内存序，synchronize-with, happens-before 这些术语，即使在国内社区，讨论的时候更多也是不翻译的。能否考虑将以上部分改回英文呢？
作者如果考虑更改这一块的话，我可以负责对 5.2 和 5.3 节这部分翻译进行一定修改。

**Comment by xiaoweiChen** [comment]
嗯，这个的确，有些中文无法很好的表述确实使用英文原文更为合适。
这里是否能做个折中，将中文翻译放在前面，后面括号中加上原来的英文原词。
比如：内存序(memory order)

这种方式感觉如何？

**Comment by mapleFU** [comment]
@xiaoweiChen 好，我会在两周内进行一些改动并pr

**Comment by xiaoweiChen** [comment]
期待你的PR
