### ISSUE TITLE
理解误差：2.1.1

### ISSUE THREAD

**Issue by FlashPanda** [xiaoweiChen/CPP-Concurrency-In-Action-2ed-2019#25]
原文：
In this case, the supplied function object is copied into the storage belonging to the
newly created thread of execution and invoked from there. It’s therefore essential that
the copy behaves equivalently to the original, or the result may not be what’s expected.

译文：
代码中，提供的函数对象会复制到新线程的存储空间当中，函数对象的执行和调用都在线程的内存空间中进行。函数对象的副本**应**与原始函数对象保持一致，否则得到的结果会与我们的期望不同。

问题：
It’s therefore指的是，所以……（blah，blah，blah）
这句话的意思是
因此，副本与原件是严格一致的，不然会出现意料之外的结果。

**Comment by xiaoweiChen** [comment]
嗯，非常感谢能指出这个短语的意思。因为本来就是非专业翻译，只是个人学习时产生的译文，所以没有太抠每个语法细节。（如果，尝试过自己个人翻译一篇500页以上外文书，你可能能理解细节会把自己拖垮）
个人理解的翻译，在如实表达作者的意图的前提下，可以进行一定程度的主观发挥。所以，不同人对同一段外文，可能有自己不同的表达。
你的表达会更严格一些，我的表达更随意一些。只要表达出了原文要表达的意思就可以了。

你觉得呢？

**Comment by FlashPanda** [comment]
这里的差别在于你翻译的句子表达出来的意思是，程序员，也就是我“应该”去维护这个这个一致性。
而原文的意思是，由于前面的这种复制机制在，所以副本和原件必然是一致的，不需要我去维护，只是说一下原理，让我这个看书的人知道罢了。

**Comment by xiaoweiChen** [comment]
懂了。所以说，读书是一件比较主观的事情嘛。翻译时，**应**只是为了保证句子的整体流畅性，读起来比较顺。其他，真没想的太多。
当然，很感谢你分享了你的看法，看到这个issue的其他同学也能多一种角度来阅读这段文字。
