### ISSUE TITLE
可以提供pdf吗？gitbook 太慢了，影响阅读

### ISSUE THREAD

**Issue by jiemojiemo** [xiaoweiChen/CPP-Concurrency-In-Action-2ed-2019#27]
我尝试过把 gitbook 转换成 pdf，但是失败了。。。

**Comment by xiaoweiChen** [comment]
https://github.com/xiaoweiChen/CPP-Concurrency-In-Action-2ed-2019/releases  
在Release里面有我转好的。

gitbook官网目前不提供离线pdf下载了。需要在本地用node.js，再安装gitbook模块，然后命令行的方式生成pdf。
可以参考这里：https://www.cnblogs.com/cottony/p/11881375.html
