### ISSUE TITLE
请问现在的翻译进度是怎么样的

### ISSUE THREAD

**Issue by Lowpower** [xiaoweiChen/CPP-Concurrency-In-Action-2ed-2019#3]
请问现在的翻译进度是怎样的，能标记一下吗？我现在看到的是第二版和第一版的内容混杂在一起

**Comment by Lowpower** [comment]
最好能在项目里标记一下那几章是翻译完的，哪些是未翻译的，引用的第一章的内容，谢谢

**Comment by xiaoweiChen** [comment]
Q: 请问现在的翻译进度是怎样的，能标记一下吗？我现在看到的是第二版和第一版的内容混杂在一起
A: 1.目前翻译全部完成。如果你有第二版英文版就会看到，其实作者在书中加入了一些新标准的内容，并未对原来内容进行过多的修改。如果没有英文原版，可以参考 https://github.com/xiaoweiChen/CPP-Concurrency-In-Action-2ed-2019/issues/1 获取一下。

Q: 最好能在项目里标记一下那几章是翻译完的，哪些是未翻译的，引用的第一章的内容，谢谢
A: 嗯，因为目前全文已经翻译完，就不存在哪些是翻译完哪些未翻译。这个库属于个人翻译，我个人并没有标记翻译进度的习惯，首先是我并不是把翻译当做一个项目在做，其次该库与gitbook同步，添加了相关进度在gitbook生成的电子书文件中也会看到，觉着这样看起来很丑，所以也没有加。
