### ISSUE TITLE
诸多的翻译不准确地方

### ISSUE THREAD

**Issue by hellolihaizhou** [xiaoweiChen/CPP-Concurrency-In-Action-2ed-2019#32]
刚看到第二章，发现翻译中诸多地方要么翻译不准确，要么翻译的没有抓住要点，要么直接省略了个别语句，有时候会给阅读者带来误导，乍一读感觉也通顺，仔细品味发现其实不然，再去看英文原版，其实原版讲的很通俗易懂，开始还以为是原版作者写的比较难懂

希望作者有空再厘清一下，翻译不合适的地方比较多，无法一一列举了

**Comment by xiaoweiChen** [comment]
有翻译不准确的地方还望指出，以便进行讨论和修改。
可以提相关语句的issue或PR，你的纠错和贡献能为后面阅读到的同学带来更多帮助。
如果觉得这个开源译版真的错误很多无法进行修改，可以选择直接阅读原作。
