### ISSUE TITLE
源代码错误

### ISSUE THREAD

**Issue by Puppas** [xiaoweiChen/CPP-Concurrency-In-Action-2ed-2019#33]
9.1节的代码清单 9.3中的第20行
原代码：
futures[i]=pool.submit(accumulate_block<Iterator,T>());
应改为:
futures[i]=pool.submit( [=] (){
     return accumulate_block<Iterator, T>()(block_start, block_end);
});

**Comment by xiaoweiChen** [comment]
感谢勘误，第二版的确如您所述。
