### ISSUE TITLE
5.3.3节的翻译错误

### ISSUE THREAD

**Issue by caiandong** [xiaoweiChen/CPP-Concurrency-In-Action-2ed-2019#36]
不好意思,提一个翻译失误.不清楚如何反馈,所以只能在这里提出来.
5.3.3节,清单5.8下方有个翻译错了,
原文是:The store to x① happens before the store to y②
译文是:存储x①先行于加载y②

提一个意见
原文:The store to x① happens before the store to y② because they’re in the same thread
译文:因为这两个操作是由同一个线程完成的，所以存储x①先行于加载y②
改为,存储x先加载于存储y,因为他们在同一个线程中,更好理解.
我体会了好久,又看了原文,才知道就是这个意思,译文缺少主语,需要靠猜测判断.虽然是这样的,但明确些更好

**Comment by caiandong** [comment]
The store to x B happens before the store to y c because
they’re in the same thread

**Comment by xiaoweiChen** [comment]
根据原文来看，的确翻译错了。

本译文由于是翻译的第一本书，只是经过本人的粗略校对，所以有些翻译的句子还是有些问题的，建议和原文一起来看。

我可能会在完成C++20/23并发相关书籍的翻译之后，抽时间重新校对本书。

非常感谢能指出来这些错误，并给译文以建议。这会给后续看本译版的同学以很大的帮助。

我会在晚些时候针对提出的问题，对相应的译文进行修改。

再次感谢！

**Comment by caiandong** [comment]
接着下面

原文:Theman in the cubicle will then duly write down this information, along with who gave him the value
译文:小隔间中的人会即使写下这一信息，以及告诉他的值

建议:小隔间中的人会及时写下这一信息以及记下是谁给了他这个值

**Comment by caiandong** [comment]
@xiaoweiChen 好的 感谢翻译
