### ISSUE TITLE
采用两端对齐

### ISSUE THREAD

**Issue by whcn** [xiaoweiChen/CPP-Concurrency-In-Action-2ed-2019#48]
提个小建议，可以使用两端对齐格式化文本后再导出pdf

**Comment by whcn** [comment]
“为了区分普通文本，清单和正文中的中的所有代码都采用 像这样的固定宽度的字体”

文中笔误：中的中的

**Comment by xiaoweiChen** [comment]
我这边没有用类似富文本的编辑器，是使用gitbook直接将md导出的pdf，所以不是很清楚你说的 两端对齐格式化 要怎么去处理。

**Comment by whcn** [comment]
Markdown支持html语法，试试下面的命令

<div style="text-align: justify"> your-text-here </div>

**Comment by whcn** [comment]
“再介绍如何给已经线程函 数传递参数，以及将线程的所有权进行移交”

笔误：如何给已经线程函 数

**Comment by xiaoweiChen** [comment]
嗯，这个可以我可以试试。

不过要整本书弄得话，还是有一些工作量的。你可以clone我的库，自己加一下相关的语句，然后生成符合自己阅读习惯的pdf。

我也只是单纯翻译学习，并不想为该书做任何宣传方面的事情。

PS. 关于笔误的可以重新开issue，方便回溯。同时也感谢勘误，有时间我会改正相关的语句。
