### ISSUE TITLE
3.2.4节翻译比较难理解的地方（或许不太对）

### ISSUE THREAD

**Issue by LimingFang** [xiaoweiChen/CPP-Concurrency-In-Action-2ed-2019#49]
在3.2.4的第三段话，原文是

> But if a fixed order is chosen (for example, the mutex for the instance supplied as the first parameter, then the mutex for the instance supplied as the second parameter), this can backfire: all it takes is for two threads to try to exchange data between the same two instances with the parameters swapped, and you have deadlock!

翻译的是：
>不过，选择一个固定的顺序(例如，实例提供的第一互斥量作为第一个参数，提供的第二个互斥量为第二个参数)，可能会适得其反：在参数交换了之后，两个线程试图在相同的两个实例间进行数据交换时，程序又死锁了！

问题主要在后半句话，但我感觉作者想表达的意思是：有两个线程需要运行该operation，第二个线程的参数和第一个线程参数的顺序是相反的，而不是说参数交换之后，这个swapped应该是指，例如第一个线程参数顺序是
`exchange(A,B)`，第二个线程参数顺序是`exchange(B,A)`
然后1A上锁，2B上锁，然后当1B试图上锁时，发生了死锁

**Comment by xiaoweiChen** [comment]
个人感觉理解有些问题哈。
可以参考本节开始那个两个小孩玩玩具的例子，现在的情况也一样。
现在已固定的锁定顺序“先锁定鼓，再锁定鼓槌“，而且孩子也要”先找到鼓，再去找鼓槌”，那么肯定不会死锁。因为只要有一个孩子没有拿到鼓，就不会去找鼓槌。
现在顺参数的顺序反过来，孩子“先去找鼓槌，再去找鼓”，那么以“先锁定鼓槌，再锁定鼓“的上锁顺序就会出现死锁。

回到你的例子：
`exchange(A,B)`，这个我认为你想表达的意思是A发生顺序先于B。
`exchange(B,A)`，这个相反，表达的意思是B发生顺序先于A。
但这里你忽略了上锁的顺序先约定好的，而不是临时决定的，所以会产生对后一句描述的疑惑。

个人认为`exchange(A,B)`这种方式的描述不是很严谨，因为在函数中A,B的顺序是不确定的，尤其在是函数或需要运行的示例时。
