### ISSUE TITLE
7.2.1节翻译问题

### ISSUE THREAD

**Issue by Tooc0ld** [xiaoweiChen/CPP-Concurrency-In-Action-2ed-2019#53]
`Unfortunately, here you don’t have that luxury; you can only safely copy the data once you know you’re the only thread returning the node, which means the node has already been removed from the queue.`
关于pop为什么不使用引用的论述。
您的翻译是
`不幸的是，不能这样做，只能在单一线程对值进行返回时，才进行拷贝以确保拷贝操作的安全性，这就意味着在拷贝结束后这个节点就会删除。`
但事实上这段话与拷贝结束没有关系。
提供一段参考：
`不幸的是，在这里你不能这样做。当线程返回这个节点时你才能安全地进行拷贝，但此刻这个节点已经从队列中被删除了。`

**Comment by xiaoweiChen** [comment]
嗯，感觉你的翻译更好一些。我修改一下。
