### ISSUE TITLE
翻译有误

### ISSUE THREAD

**Issue by mingjitianming** [xiaoweiChen/CPP-Concurrency-In-Action-2ed-2019#56]
你好，首先感谢您所做的工作！
1.在第九章代码9.2末尾的注释我的理解应该是“其余同前”的意思，这样是否更合理
2.在清单9.2下面的“因为能并发执行，最小工作块值的一试”，应该是”值得一试“

**Comment by xiaoweiChen** [comment]
感谢勘误！
1. 这个的确是和 之前相同 的意思。
2. “因为能并发执行，最小工作块值的一试”这句话我没有找到。

**Comment by mingjitianming** [comment]
> 感谢勘误！
> 
> 1. 这个的确是和 之前相同 的意思。
> 2. “因为能并发执行，最小工作块值的一试”这句话我没有找到。

不好意思，我看的貌似是之前的版本，已经被纠正过了，非常感谢
