### ISSUE TITLE
关于listing 翻译的建议

### ISSUE THREAD

**Issue by zhourongtu** [xiaoweiChen/CPP-Concurrency-In-Action-2ed-2019#58]
listing在文中部分区域，被翻译为清单。

在列出代码时，称作”代码“。

两处的翻译不一致是有一点点令人难受的。

**Comment by xiaoweiChen** [comment]
在最后一次校对时，将“清单”全部改成了“代码”，感觉这样读起来更好一些。

其中有些地方可能遗漏了，没有改过来，如若发现请提issue或PR。

感谢建议！
