### ISSUE TITLE
7.1.3 无等待数据结构

### ISSUE THREAD

**Issue by weikano** [xiaoweiChen/CPP-Concurrency-In-Action-2ed-2019#6]
翻译
> 由于会和别的线程产生冲突，所以算法可以进行无数次尝试，因此并不是无等待的

原文
> Algorithms that can involve an unbounded number of retries because of clashes with other threads are thus not wait-free

建议
> 如果因为跟其他线程冲突而导致算法会进行无数次重试，那么就不是无等待的

**Comment by weikano** [comment]
还有下面那段
> 正确实现一个无锁的结构十分苦难

原文
> Writing wait-free data structures correctly is extremely hard

建议
> 实现一个无等待的结构十分困难

无等待和无锁还是有区别的

**Comment by weikano** [comment]
额。后面的那段翻译的不太妥当
> 要保证每一个线程都能在有限的时间里完成操作，就需要保证每一个操作可以被一次性执行完；当线程执行到某个操作时，应该不会让其他线程的操作失败

原文是
> In order to ensure that every thread can complete its operations within a bounded number of steps, you have to ensure that each operation can be performed in a single pass and that the steps performed by one thread don’t cause an operation on another thread to fail

建议
> 要保证每个线程都能在有限的步骤内完成操作，你必须确保每次执行的操作都是一次性的(a single pass不知道怎么翻译好)，并且任意一个线程的操作不会导致其他线程的操作失败

还有
> 考虑到获取无锁或无等待的数据结构所有权都很困难
应该是
> 考虑到正确的实现一个无锁或者无等待的数据结构都很困难

**Comment by xiaoweiChen** [comment]
1. 我修改成以下的方式，可能有些冗余的描述，但感觉这样更有助于读者理解：
> 由于可能会和其他线程的行为冲突，从而算法会进行了若干次尝试，因此无法做到无等待。

2. 这里是一个错误，感谢指出。

3. single pass的意思可以参考这里的解释：
    https://stackoverflow.com/questions/13113721/how-is-the-term-single-pass-defined
    “使用不可递归和迭代的操作获取一个对象(元素)”，个人觉得为了简单易懂，翻译成“操作”即可。
    > 正确实现一个无等待结构十分困难的，要保证每个线程都能在有限的步骤内完成操作，你必须确保每次执行的操作都是一次性的，并且当前线程中的操作不会影响其他线程的操作。

4. 我对你的翻译持保留意见，感觉有点太直译原文了，下面是我修改的
> 考虑到获取无锁或无等待的数据结构所有权非常困难，那么就实现一个数据结构吧。不过，需要保证所要得获益要大于实现成本，那就先来找一下实现成本和所得获益的平衡点吧！

**Comment by weikano** [comment]
第4点理解错了吧
> Given how hard it is to get a lock-free or wait-free data structure right

这里的right是正确的意思，没有所有权的意思

**Comment by xiaoweiChen** [comment]
嗯，懂了。你的重点在right上。

> 考虑到实现无锁或无等待的数据结构非常困难，索性就实现一个数据结构吧。不过，需要保证收益要大于成本，那么就先来找一下成本和收益的平衡点吧！

改成了以上的语句，已经提交。
