### ISSUE TITLE
关于先前的2.3，翻译有误处的想法

### ISSUE THREAD

**Issue by zhourongtu** [xiaoweiChen/CPP-Concurrency-In-Action-2ed-2019#60]
看到译者在改成了

> std::thread中对移动语义的支持，也适用于使用std::thread的移动敏感(move-aware)容器(比如，std::vector<>)。了解这些后，就可以量产了一些线程，并且等待它们结束，代码如下所示。

我其实想强调一点，就是准确。

std::thread支持移动语义，这使得使用std::thread的容器对象（std::vector<>）在使用std::thread作为容器类型时，同样是移动敏感的。

在C++11中提出了右值引用、移动语义，在STL中完美实现了这一点，在利用移动拷贝构造函数时，移动赋值构造函数时，都能实现移动语义。此时STL能够利用std::thread内部实现的移动语义去实现这样的移动构造函数，减少相应的开销。

原文中的核心在于：了解这一点，就可以利用这一条性质去利用容器量产线程（通过容器的元素构造形式去量产线程）

代码中采用了emplace_back去生成相应的线程，实际上这里的emplace_back利用的是“完美转发”，将所有的参数直接转发到std::thread的构造函数去，而完美转发的实现依赖于移动语义。

这意味着一点，std::thread不能拷贝形成。

我非常想拿我前段时间写的一些代码做例子去阐述这一点。否则这令我有点头疼，下面是我写的一个小例子与相关的结果

![image](https://user-images.githubusercontent.com/39449244/105949989-9675b200-60a8-11eb-9c46-4d13c8287eb9.png)

![image](https://user-images.githubusercontent.com/39449244/105950022-a5f4fb00-60a8-11eb-9b83-c628a7b9411d.png)

![image](https://user-images.githubusercontent.com/39449244/105950051-b0af9000-60a8-11eb-923c-2fc02bcadafc.png)

![image](https://user-images.githubusercontent.com/39449244/105950082-bd33e880-60a8-11eb-9828-6c6061be1cf8.png)

这样的一个例子阐述了移动语义在类似情况下的应用，这本书在阐述std::thread的不可拷贝之类的属性的时候，强调的就是std::thread通过移动语义转移所有权，这和unique_ptr类似。

希望我的解释能帮到你，（主要是翻译让我感到头疼，上一次也是我第一次提issue，如有不当，请指出。）

**Comment by zhourongtu** [comment]
我突然觉得可能是我太钻牛角尖了。

或许有些东西本身就需要补充才能更清楚......

啊，反正就是希望以后如果翻译的话，能够完整点。

**Comment by xiaoweiChen** [comment]
哈哈，我先回复你这个issue吧。

对于你的试验结果，和对准确性的要求，我认为没有问题，也不想太多讨论。
但我这本书的翻译并不是以这个为目标的，这里仅仅就是我自己在学习多线程时的一个中间结果的展现。

嗯，如果作为纯翻译来说，我的这个译版是不合格的。因为只有我个人的看法，对于翻译我肯定加了我自己对于文字的理解。
不过我的翻译都不是作为纯翻译来做的，我只是当做自己的爱好，自己的学习成果而已。

我很高兴看到有人愿意和我讨论其中的内容，但不是特别喜欢和别人做文字上的博弈。
因为文字是抽象的东西，每个人的不同经历，会赋予文字不同的理解。

这个译版被喷过很多次了，你可以去知乎上看看我收到的部分回复 https://www.zhihu.com/question/30432095 

Readme里云风的那段话很能代表我的感受：
> 翻译是译者用自己的思想，换一种语言，对原作者想法的重新阐释。鉴于我的学识所限，误解和错译在所难免。如果你能买到本书的原版，且有能力阅读英文，请直接去读原文。因为与之相较，我的译文可能根本不值得一读。

如果我的译版确实无法帮助你，你自己有能力的话可以选择看原版，或选择其他译版。

不知道以后还会不会再翻译这种书籍，也许不会了吧，就算会也许不会再开源出来了。
