### ISSUE TITLE
8.2.2

### ISSUE THREAD

**Issue by weikano** [xiaoweiChen/CPP-Concurrency-In-Action-2ed-2019#9]
原翻译
> counter变量是全局的，所以任何线程都能调用processing_loop()去修改同一个变量。因此，当新增加的处理器时，counter变量必须要在缓存内做一份拷贝，再改变自己的值，或其他线程以发布的方式对缓存中的拷贝副本进行更新

 原文
> The counter is global, so any threads that call processing_loop() are modifying the same variable. Therefore, for each increment the processor must ensure it has an upto-date copy of counter in its cache, modify the value, and publish it to other processors.

建议
> counter变量是全局的，所以任何调用procecssing_loop的线程都是在修改同一个变量。因此，每次对counter进行增量操作时，处理器都必须确保缓存中的counter是最新的值，然后修改告知其他处理器

**Comment by xiaoweiChen** [comment]
感谢勘误! 这里的确是翻译的时候理解错误。
